export const ROUTES = {
  HOME: '/',
  PETS: '/pets',
  PET_DETAIL: '/pets/:id',
  FOUNDATIONS: '/foundations',
  FOUNDATION_DETAIL: '/foundations/:id',
  ADOPT: '/adopt/:petId',
  MY_ADOPTIONS: '/my-adoptions',
  LOGIN: '/login',
  REGISTER: '/register',
  FOUNDATION_DASHBOARD: '/foundation/dashboard',
  AI: '/ai',
  ADMIN: '/admin',
  DEVELOPER_DASHBOARD: '/developer/dashboard',
  PENDING: '/pending',
  REJECTED: '/rejected',
  ACCOUNT: '/account',
} as const;
